DROP TABLE IF EXISTS list CASCADE;

CREATE TABLE list (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  productName VARCHAR(255) NOT NULL,
  openedOn DATE NOT NULL,
  useBy DATE NOT NULL
);